"""fix roomfacilitiesorm column name

Revision ID: e651a0001606
Revises: 4cd48ebda634
Create Date: 2024-10-14 11:35:55.437600

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e651a0001606"
down_revision: Union[str, None] = "4cd48ebda634"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rooms_facilities", sa.Column("facility_id", sa.Integer(), nullable=False))
    op.drop_constraint(
        "rooms_facilities_facilities_id_fkey", "rooms_facilities", type_="foreignkey"
    )
    op.create_foreign_key(None, "rooms_facilities", "facilities", ["facility_id"], ["id"])
    op.drop_column("rooms_facilities", "facilities_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "rooms_facilities",
        sa.Column("facilities_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "rooms_facilities", type_="foreignkey")
    op.create_foreign_key(
        "rooms_facilities_facilities_id_fkey",
        "rooms_facilities",
        "facilities",
        ["facilities_id"],
        ["id"],
    )
    op.drop_column("rooms_facilities", "facility_id")
    # ### end Alembic commands ###
